version: '3'

services:
  redis:
    container_name: marketplace-redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
    networks:
      - marketplace

  postgres:
    container_name: marketplace-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=marketplace-user
      - POSTGRES_PASSWORD=marketplace-pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '15432:5432'
    networks:
      - marketplace

  adonis:
    container_name: marketplace-app-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    networks:
      - marketplace

networks:
  marketplace:
    driver: bridge
    external: true
